name: Bump Version

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        default: patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs: 
      new_ver: ${{ steps.bump.outputs.new_ver }}
      old_ver: ${{ steps.bump.outputs.old_ver }}
      part: ${{ steps.bump.outputs.part }}
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install bump2version
      run: python -m pip install bump2version
      uses: actions/checkout@v2
    - name: Bump version
      id: bump
      uses: ./
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: v${{ needs.bump-version.outputs.new_ver }}
          release_name: Release v${{ needs.bump-version.outputs.new_ver }}
          draft: false
          prerelease: false

