name: Create Release and File

on:
  workflow_dispatch:
    inputs: 
      version:
        description: 'version number'
        required: true
        default: 0.3.25
        
jobs:
  Create_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: process1
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Check for version.cfg
      id: get-current-version
      run: |
        if [ ! -f version.cfg ]; then
           echo "Current_version = ${{ github.event.inputs.version }}" >> version.cfg        
        fi
        echo "::set-output name=current_version::$(cat version.cfg | cut -c 20-26)"
    - name: Bump Version
      id: version-changed
      if: steps.get-current-version.outputs.current_version != ${{ github.event.inputs.version }}
      run: |
        sed -i 's/${{ steps.get-current.version.outputs.current_version }}/${{ github.event.inputs.version }}/g' version.cfg
    - name: Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: release/${{ github.event.inputs.version }}
        commit-message: 'chore: release ${{ github.event.inputs.version }}'
        base: main
        labels: chore
        reviewers: M5Skid
        assignees: M5Skid
        body: |
          Releasing ${{ github.event.inputs.version }}.
