name: Create version file

on:
  workflow_dispatch:
    inputs: 
      version:
        description: 'version number'
        required: true
        default: 0.3.25
        
jobs:
  make-file:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: process1
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Create version file
      run: |
        echo 'Current Version "${version}"' >> version.cfg
    - name: Create pull request into prod
      uses: peter-evans/create-pull-request@v3
      with:
        branch: release/${version}
        commit-message: 'chore: release ${version}'
        base: main
        ftitle: Release ${version}
        labels: chore
        reviewers: M5Skid
        assignees: M5Skid
        body: |
          Releasing ${version}.
